import { expect, test, type Locator, type Page } from '@playwright/test';

/**
 * Functional gate for the claims this lab makes on screen.
 *
 * The a11y spec proves the page is reachable; this one proves it is RIGHT.
 * The vitest suite covers the DRBGs, the P-256 arithmetic, the NIST tests and
 * the two UI renderers in isolation — but nothing covered the assembled page:
 * the counters, the heatmap against the hex it was drawn from, the stats table,
 * the KAT tally, the ABOUT trapdoor readout, or the attack theater's closing
 * verdict. Those only exist in a browser.
 *
 * The load-bearing assertions here are the cross-path ones:
 *   - the heatmap's 1-bit count == the popcount of the hex string above it
 *   - the intercepted blocks the attack works from == the two blocks the test
 *     just generated by clicking Generate
 *   - the "YOUR MOVE" predicted hex == the output of the NEXT Generate click
 *   - ABOUT's "d·Q computed just now" == ABOUT's rendered P.x
 *   - the closing verdict's "X of Y predictions matched" == the tally of ✅ rows
 *   - the KAT modal's "N/M vectors passed" == the tally of PASS rows
 *   - every stats cell's ✅/❌ == its own p-value against the 0.01 threshold
 */

const HMAC = 0;
const CHACHA = 1;
const DUAL_EC = 2;
const ALGO_NAMES = ['HMAC-DRBG', 'ChaCha20-DRBG', 'Dual_EC_DRBG'];

const panels = (page: Page): Locator => page.locator('.three-panel > .panel');
const panel = (page: Page, i: number): Locator => panels(page).nth(i);
const output = (page: Page, i: number): Locator => panel(page, i).locator('.hex-output');
const generateBtn = (page: Page, i: number): Locator =>
  panel(page, i).getByRole('button', { name: /^Generate/ });
const reseedBtn = (page: Page, i: number): Locator =>
  panel(page, i).getByRole('button', { name: /^Reseed/ });
/** The state line ("reseed_counter: N"). */
const stateLine = (page: Page, i: number): Locator =>
  panel(page, i)
    .locator('div')
    .filter({ hasText: /^(reseed_counter|Not yet instantiated)/ })
    .first();
/**
 * The prediction badge is appended to the Dual_EC panel as the last element of
 * initUI, and stays display:none until an attack arms a prediction.
 */
const predictBadge = (page: Page): Locator => panel(page, DUAL_EC).locator('> div').last();

const text = async (locator: Locator): Promise<string> =>
  ((await locator.textContent()) ?? '').replace(/ /g, ' ').trim();

/** Number of 1 bits in a hex string. */
const popcount = (hex: string): number => {
  let ones = 0;
  for (const ch of hex) {
    let nibble = Number.parseInt(ch, 16);
    while (nibble > 0) {
      ones += nibble & 1;
      nibble >>= 1;
    }
  }
  return ones;
};

/**
 * initUI harvests entropy and instantiates all three DRBGs before it wires a
 * single button, so a click that lands inside that window does nothing at all.
 * Keep clicking Generate on the first panel until it really produces output —
 * once any panel is wired all three are, they are wired in one sync block.
 */
async function waitForGenerators(page: Page): Promise<void> {
  await expect(panels(page)).toHaveCount(3);
  await expect
    .poll(
      async () => {
        await generateBtn(page, HMAC).click();
        await page.waitForTimeout(120);
        return await text(output(page, HMAC));
      },
      { timeout: 30_000 }
    )
    .not.toBe('—');
}

/* ------------------------------------------------------ the three panels */

test('renders three generators, only one of which is armed with an attack', async ({ page }) => {
  await page.goto('.');
  await waitForGenerators(page);

  for (let i = 0; i < 3; i += 1) {
    await expect(panel(page, i).locator('.panel-header')).toContainText(ALGO_NAMES[i]);
  }
  await expect(panel(page, DUAL_EC)).toContainText('COMPROMISED');
  // The attack belongs to the backdoored generator and to nothing else.
  await expect(panel(page, DUAL_EC).locator('.btn-danger')).toHaveCount(1);
  await expect(panel(page, HMAC).locator('.btn-danger')).toHaveCount(0);
  await expect(panel(page, CHACHA).locator('.btn-danger')).toHaveCount(0);

  await generateBtn(page, CHACHA).click();
  await generateBtn(page, DUAL_EC).click();
  for (let i = 0; i < 3; i += 1) {
    await expect(output(page, i)).not.toHaveText('—');
  }

  const hex = [await text(output(page, HMAC)), await text(output(page, CHACHA)), await text(output(page, DUAL_EC))];
  for (const h of hex) {
    expect(h).toMatch(/^[0-9a-f]+$/);
  }
  // The two honest panels request 256 bits; Dual_EC emits the low 30 bytes of
  // r, which is what makes the 16-bit leak the attack exploits.
  expect(hex[HMAC].length / 2).toBe(32);
  expect(hex[CHACHA].length / 2).toBe(32);
  expect(hex[DUAL_EC].length / 2).toBe(30);

  // Only the backdoored stream is styled as corrupted.
  await expect(output(page, DUAL_EC)).toHaveClass(/corrupted/);
  await expect(output(page, HMAC)).not.toHaveClass(/corrupted/);
  await expect(output(page, CHACHA)).not.toHaveClass(/corrupted/);
});

test('each heatmap is a function of the bytes printed above it, and of nothing else', async ({
  page
}) => {
  await page.goto('.');
  await waitForGenerators(page);
  await generateBtn(page, CHACHA).click();
  await generateBtn(page, DUAL_EC).click();
  for (let i = 0; i < 3; i += 1) {
    await expect(panel(page, i).locator('.bit-grid')).toBeVisible();
  }

  const litColours: string[] = [];
  for (let i = 0; i < 3; i += 1) {
    const hex = await text(output(page, i));
    const grid = panel(page, i).locator('.bit-grid');
    const cells = await grid.locator('.bit-cell').count();
    const lit = await grid.locator('.bit-cell.bit-1').count();
    const dark = await grid.locator('.bit-cell.bit-0').count();

    // Every bit is drawn exactly once: the parts sum to the whole.
    expect(lit + dark).toBe(cells);
    // The grid is sized to the data — no zero-padded row. 30 bytes => 240 cells.
    expect(cells).toBe((hex.length / 2) * 8);
    expect(cells % 16).toBe(0);
    // Ground truth: the lit cells are the 1 bits of the hex string on screen.
    expect(lit).toBe(popcount(hex.slice(0, cells / 4)));

    // The aria-label must state that same measurement, to the same precision.
    const label = (await grid.getAttribute('aria-label')) ?? '';
    const parsed = label.match(
      /Bit pattern from (.+): (\d+) bits, (\d+) of them 1 \((\d+\.\d)%\)\./
    );
    expect(parsed, `heatmap label was: ${label}`).not.toBeNull();
    expect(parsed?.[1]).toBe(ALGO_NAMES[i]);
    expect(Number(parsed?.[2])).toBe(cells);
    expect(Number(parsed?.[3])).toBe(lit);
    expect(parsed?.[4]).toBe(((lit / cells) * 100).toFixed(1));

    expect(lit).toBeGreaterThan(0);
    litColours.push(
      await grid
        .locator('.bit-cell.bit-1')
        .first()
        .evaluate((el) => getComputedStyle(el).backgroundColor)
    );
  }

  // The page's whole thesis is that the three streams are indistinguishable.
  // A lit bit must therefore be the same colour whichever generator drew it —
  // this is a computed style, so only a browser can check it.
  expect(litColours[CHACHA]).toBe(litColours[HMAC]);
  expect(litColours[DUAL_EC]).toBe(litColours[HMAC]);
});

test('reseed_counter counts the Generate clicks and resets on reseed', async ({ page }) => {
  await page.goto('.');
  await waitForGenerators(page);

  const counter = async (i: number): Promise<number> =>
    Number.parseInt((await text(stateLine(page, i))).match(/reseed_counter: (\d+)/)?.[1] ?? '', 10);

  for (const i of [HMAC, CHACHA, DUAL_EC]) {
    if (i !== HMAC) {
      await generateBtn(page, i).click();
      await expect(output(page, i)).not.toHaveText('—');
    }
    const before = await counter(i);
    expect(before).toBeGreaterThanOrEqual(1);

    await generateBtn(page, i).click();
    await expect.poll(() => counter(i)).toBe(before + 1);
    await generateBtn(page, i).click();
    await expect.poll(() => counter(i)).toBe(before + 2);

    // Reseeding restarts the counter and says so.
    await reseedBtn(page, i).click();
    await expect(stateLine(page, i)).toHaveText(/reseed_counter: 1 \(reseeded\)/);
  }
});

/* --------------------------------------------------- statistical tests */

type StatCell = { icon: string; p: number; raw: string };

async function readStatTable(page: Page): Promise<{ names: string[]; cells: StatCell[][] }> {
  const rows = await page.locator(".stat-table:not([data-stale]) tbody tr").evaluateAll((trs) =>
    trs.map((tr) => Array.from(tr.children).map((td) => (td.textContent ?? '').trim()))
  );
  return {
    names: rows.map((r) => r[0]),
    cells: rows.map((r) =>
      r.slice(1).map((raw) => {
        const m = raw.match(/^(✅|❌) p=([<>]?[\d.]+)$/);
        const shown = m?.[2] ?? '';
        // "<x" means strictly below x, ">x" strictly above; take the closest
        // value each could stand for so the threshold check stays exact.
        let p = Number(shown);
        if (shown.startsWith('<')) p = Number(shown.slice(1));
        if (shown.startsWith('>')) p = Number(shown.slice(1)) + 1e-9;
        return { icon: m?.[1] ?? '', p, raw };
      })
    )
  };
}

/**
 * Click "Run Tests" and wait for a table this click produced. Marking the
 * previous table stale first matters: the handler leaves the old table on
 * screen while it samples, so a re-run that simply waits for `.stat-table`
 * reads the PREVIOUS result and never re-samples at all.
 */
async function runStats(page: Page): Promise<void> {
  await page
    .locator('.stat-table')
    .evaluateAll((tables) => tables.forEach((t) => t.setAttribute('data-stale', '1')));
  await page.locator('#btn-run-stats').click();
  await expect(page.locator('.stat-table:not([data-stale])')).toBeVisible({ timeout: 120_000 });
}

test('every statistical verdict agrees with its own p-value', async ({ page }) => {
  test.setTimeout(180_000);
  await page.goto('.');
  await waitForGenerators(page);
  await generateBtn(page, CHACHA).click();
  await generateBtn(page, DUAL_EC).click();

  await expect(page.locator('#stats-output')).toContainText('then run statistical tests');
  await runStats(page);

  const headers = await page.locator('.stat-table thead th').allTextContents();
  expect(headers.map((h) => h.trim())).toEqual(['Test', ...ALGO_NAMES]);

  const { names, cells } = await readStatTable(page);
  expect(names).toEqual([
    'Frequency (Monobit)',
    'Block Frequency',
    'Runs',
    'Longest Run of Ones'
  ]);

  expect(cells).toHaveLength(4);
  for (const row of cells) {
    // One verdict per algorithm, no column skipped or special-cased.
    expect(row).toHaveLength(3);
    for (const cell of row) {
      expect(cell.icon, `unparsable cell: ${cell.raw}`).toMatch(/^(✅|❌)$/);
      expect(Number.isFinite(cell.p)).toBe(true);
      expect(cell.p).toBeGreaterThanOrEqual(0);
      expect(cell.p).toBeLessThanOrEqual(1);
      // NIST SP 800-22 calls it a pass at p > 0.01. The icon must be that
      // comparison and not an opinion about the algorithm.
      expect(cell.icon === '✅', `p=${cell.raw} on the wrong side of 0.01`).toBe(cell.p > 0.01);
    }
  }
});

test('the backdoored generator passes the same battery as the honest two', async ({ page }) => {
  test.setTimeout(240_000);
  await page.goto('.');
  await waitForGenerators(page);
  await generateBtn(page, CHACHA).click();
  await generateBtn(page, DUAL_EC).click();

  // This is the page's central claim, and it is a statistical one: under the
  // null hypothesis each test fails ~1% of the time BY DESIGN, so a single
  // sample can legitimately show a red cell. Draw fresh samples until a clean
  // sweep appears; five independent misses would be a ~1-in-50,000 event, and
  // a genuinely non-random stream would never produce a clean sweep at all.
  let allPassed: string[][] = [];
  for (let attempt = 0; attempt < 5; attempt += 1) {
    await runStats(page);
    const { cells } = await readStatTable(page);
    allPassed = cells.map((row) => row.map((c) => c.icon));
    if (allPassed.every((row) => row.every((icon) => icon === '✅'))) {
      break;
    }
  }
  expect(allPassed).toEqual([
    ['✅', '✅', '✅'],
    ['✅', '✅', '✅'],
    ['✅', '✅', '✅'],
    ['✅', '✅', '✅']
  ]);
});

/* ------------------------------------------------------------- KAT modal */

test('the KAT modal tally is the number of vectors that actually passed', async ({ page }) => {
  await page.goto('.');
  await waitForGenerators(page);

  await page.locator('#btn-kat').click();
  const modal = page.locator('.modal-backdrop .modal-content');
  await expect(modal.locator('.stat-table tbody tr').first()).toBeVisible({ timeout: 60_000 });

  const summary = await text(modal.locator('p').first());
  const parsed = summary.match(/^(\d+)\/(\d+) vectors passed/);
  expect(parsed, `KAT summary was: ${summary}`).not.toBeNull();
  const claimedPassed = Number(parsed?.[1]);
  const claimedTotal = Number(parsed?.[2]);

  const rows = await modal.locator('.stat-table tbody tr').evaluateAll((trs) =>
    trs.map((tr) => Array.from(tr.children).map((td) => (td.textContent ?? '').trim()))
  );
  // The table is the evidence for the tally: row count is the total, and the
  // PASS rows are the numerator.
  expect(rows).toHaveLength(claimedTotal);
  expect(rows.filter((r) => r[1].includes('PASS')).length).toBe(claimedPassed);
  expect(claimedPassed).toBe(claimedTotal);

  for (const row of rows) {
    expect(row[0]).toMatch(/^CAVS-SHA256-PR-False-Count\d$/);
    expect(row[1]).toBe('✅ PASS');
    // A PASS row must show the same bytes in both columns.
    expect(row[2]).toBe(row[3]);
    expect(row[2]).toMatch(/^[0-9a-f]{16}\.\.\.$/);
  }
  // A pass with no failures must not carry the failure advisory.
  expect(summary).not.toContain('check implementation');
  await expect(modal).toContainText('NIST CAVS 14.3 HMAC_DRBG(SHA-256)');

  await modal.getByRole('button', { name: /close/i }).click();
  await expect(page.locator('.modal-backdrop')).toHaveCount(0);
});

/* ----------------------------------------------------------- ABOUT modal */

test('ABOUT proves the trapdoor live: d·Q renders as the same point as P', async ({ page }) => {
  await page.goto('.');
  await waitForGenerators(page);

  await page.locator('#btn-about').click();
  const modal = page.locator('.modal-backdrop .modal-content');
  await expect(modal).toBeVisible();
  const constants = (await modal.innerText()).replace(/\u00a0/g, ' ');

  const pX = constants.match(/P \(P-256 generator\)\.x = (0x[0-9a-f]+…[0-9a-f]+)/)?.[1];
  const nistQx = constants.match(/NIST Q \(published\)\.x = (0x[0-9a-f]+…[0-9a-f]+)/)?.[1];
  const dQx = constants.match(/d·Q computed just now → x = (0x[0-9a-f]+…[0-9a-f]+)/)?.[1];
  expect(pX, `constants block was: ${constants}`).toBeTruthy();
  expect(nistQx).toBeTruthy();
  expect(dQx).toBeTruthy();

  // The whole backdoor rests on d·Q = P. The page multiplies it out on open;
  // the result it prints must be the P it prints two lines above.
  expect(dQx).toBe(pX);
  expect(constants).toContain('✓ trapdoor verified live');
  expect(constants).not.toContain('✗');
  // The real published Q is shown, unused, and is a different point.
  expect(nistQx).not.toBe(pX);

  await modal.getByRole('button', { name: /close/i }).click();
  await expect(page.locator('.modal-backdrop')).toHaveCount(0);
});

/* ---------------------------------------------------------- the attack */

test('no prediction is claimed before the attack has been run', async ({ page }) => {
  await page.goto('.');
  await waitForGenerators(page);
  await generateBtn(page, DUAL_EC).click();
  await expect(output(page, DUAL_EC)).not.toHaveText('—');

  await expect(page.locator('#attack-container')).toBeHidden();
  await expect(predictBadge(page)).toBeHidden();
});

test('the attack recovers state from the blocks you generated and predicts your next click', async ({
  page
}) => {
  test.setTimeout(300_000);
  await page.goto('.');
  await waitForGenerators(page);

  // Generate the "intercepted traffic" ourselves so we know exactly what the
  // attacker is entitled to see.
  await generateBtn(page, DUAL_EC).click();
  await expect(output(page, DUAL_EC)).not.toHaveText('—');
  const blockA = await text(output(page, DUAL_EC));
  await generateBtn(page, DUAL_EC).click();
  await expect.poll(async () => await text(output(page, DUAL_EC))).not.toBe(blockA);
  const blockB = await text(output(page, DUAL_EC));
  expect(blockB).not.toBe(blockA);

  await panel(page, DUAL_EC).locator('.btn-danger').click();
  const theater = page.locator('.attack-overlay');
  await expect(theater).toBeVisible();
  await expect(theater).toContainText('STATE RECOVERED', { timeout: 240_000 });

  // The attacker works from YOUR output — the two most recent blocks, verbatim.
  const overlay = (await theater.innerText()).replace(/ /g, ' ');
  expect(overlay.match(/block 1\s+([0-9a-f]+)/)?.[1]).toBe(blockA);
  expect(overlay.match(/block 2\s+([0-9a-f]+)/)?.[1]).toBe(blockB);
  // The prose's block size must be the block size actually on the wire.
  expect(overlay).toContain(`two consecutive ${blockB.length / 2}-byte output blocks`);
  expect(overlay).toContain(`Each output reveals ${(blockB.length / 2) * 8} of 256 bits`);

  // The search reports a real, bounded candidate count.
  const searched = overlay.match(/Searched ([\d,]+) candidates in /)?.[1];
  expect(searched, `progress label missing from: ${overlay}`).toBeTruthy();
  const candidates = Number.parseInt((searched ?? '').replace(/,/g, ''), 10);
  expect(candidates).toBeGreaterThan(0);
  expect(candidates).toBeLessThanOrEqual(65536);
  expect(overlay).toMatch(/STATE RECOVERED: s = 0x[0-9a-f]+/);

  // The bar and its accessible value must agree that the search is finished.
  const bar = theater.locator('[role="progressbar"]');
  await expect(bar).toHaveAttribute('aria-valuenow', '100');
  expect(await theater.locator('.progress-fill').evaluate((el) => el.style.width)).toBe('100%');

  // Ten predictions, verified one row at a time.
  await expect(theater.locator('.prediction-row')).toHaveCount(11, { timeout: 120_000 });
  const rows = (
    await theater
      .locator('.prediction-row')
      .evaluateAll((els) => els.map((el) => Array.from(el.children).map((c) => (c.textContent ?? '').trim())))
  ).filter((r) => r[0] !== 'PREDICTED');
  expect(rows).toHaveLength(10);
  for (const [predicted, actual, match] of rows) {
    expect(predicted).toMatch(/^[0-9a-f]{20}\.\.\.$/);
    // A ✅ must mean the two columns beside it are equal.
    expect(match === '✅').toBe(predicted === actual);
    expect(match).toBe('✅');
  }

  // The closing verdict is the tally of those rows, not a fixed headline. The
  // "YOUR MOVE" callout is written last, so waiting for it settles the panel.
  await expect(theater).toContainText('YOUR MOVE', { timeout: 60_000 });
  const summaryText = (await theater.innerText()).replace(/ /g, ' ');
  const tally = summaryText.match(/(TOTAL COMPROMISE|PARTIAL) — (\d+) of (\d+) predictions matched/);
  expect(tally, `no verdict found in: ${summaryText}`).not.toBeNull();
  const matched = Number(tally?.[2]);
  const total = Number(tally?.[3]);
  expect(total).toBe(rows.length);
  expect(matched).toBe(rows.filter((r) => r[2] === '✅').length);
  expect(tally?.[1] === 'TOTAL COMPROMISE').toBe(matched === total);
  expect(tally?.[1]).toBe('TOTAL COMPROMISE');

  // The body's arithmetic: N blocks at 240 bits each.
  const bits = summaryText.match(/From (\d+) intercepted output blocks — (\d+) bits/);
  expect(bits).not.toBeNull();
  expect(Number(bits?.[1])).toBe(2);
  expect(Number(bits?.[2])).toBe(Number(bits?.[1]) * 240);

  // The rate quoted in the summary is the rate the timing line measured, not a
  // constant standing in for one.
  const summaryRate = summaryText.match(/at ([\d,]+) candidates\/sec in this tab/)?.[1];
  const timingRate = summaryText.match(/· ([\d,]+) candidates\/sec in this browser tab/)?.[1];
  expect(summaryRate).toBeTruthy();
  expect(summaryRate).toBe(timingRate);

  /* --- and now the headline claim: it predicts your NEXT click --- */

  const predictedNext = summaryText.match(/next Generate click will output:\s*\n?\s*([0-9a-f]{60})/)?.[1];
  expect(predictedNext, `YOUR MOVE hex missing from: ${summaryText}`).toBeTruthy();
  await expect(predictBadge(page)).toBeVisible();
  await expect(predictBadge(page)).toContainText(
    `Attacker's prediction for your NEXT Generate: ${(predictedNext ?? '').slice(0, 24)}…`
  );
  // The armed prediction is the first verified row.
  expect(rows[0][0]).toBe(`${(predictedNext ?? '').slice(0, 20)}...`);

  const beforeClick = await text(output(page, DUAL_EC));
  expect(beforeClick).not.toBe(predictedNext);
  await generateBtn(page, DUAL_EC).click();
  await expect.poll(async () => await text(output(page, DUAL_EC))).not.toBe(beforeClick);

  // THE claim: the bytes the generator just produced are the bytes the attacker
  // wrote down before the click.
  expect(await text(output(page, DUAL_EC))).toBe(predictedNext);
  await expect(predictBadge(page)).toContainText(
    'The attacker predicted this exact output before you clicked'
  );
  const nextPredicted = (await text(predictBadge(page))).match(/Next predicted: ([0-9a-f]{24})…/)?.[1];
  expect(nextPredicted).toBeTruthy();
  expect(rows[1][0]).toBe(`${(nextPredicted ?? '').slice(0, 20)}...`);

  /* --- reseeding revokes the attacker's knowledge --- */

  await reseedBtn(page, DUAL_EC).click();
  await expect(stateLine(page, DUAL_EC)).toHaveText(/reseed_counter: 1 \(reseeded\)/);
  await expect(predictBadge(page)).toBeHidden();

  const afterReseed = await text(output(page, DUAL_EC));
  await generateBtn(page, DUAL_EC).click();
  await expect.poll(async () => await text(output(page, DUAL_EC))).not.toBe(afterReseed);
  // Fresh entropy means the queued prediction is worthless and is not claimed.
  await expect(predictBadge(page)).toBeHidden();
  expect(await text(output(page, DUAL_EC))).not.toContain(nextPredicted ?? 'unreachable');
});
